### ISSUE TITLE
Noisy data from camera

### ISSUE THREAD

**Issue by CrashTestCoder** [TEAM1771/2021-Code#16]
This might not be a problem, but we should solve this problem now so we can fix it quickly if we decide it needs to be done

Ultimately we need to be able to use the average of the past few camera results

We need some functon/object that we can call and pass the new data to it, and it will return the average of the past few data points

**Comment by CrashTestCoder** [comment]
This is the sort of thing that is best debugged in a separate project (separate from robot code) compiled and run locally on your computer

**Comment by MrRedness** [comment]
I tried to use vectors at first for more flexibility, but as you can see in the commented out section, it did not go very well.

**Comment by CrashTestCoder** [comment]
Looks good, the only change id make is instead of putting it in double Average::average(double) I'd put it in double operator() (double). Which would serve to make the call look a little nicer

**Comment by MrRedness** [comment]
Or did you mean double operator(double input)

**Comment by MrRedness** [comment]
Oh oof it took you 3 min to write up what took me 3 hours
