### ISSUE TITLE
Swerve Velocity Control

### ISSUE THREAD

**Issue by CrashTestCoder** [TEAM1771/2021-Code#4]
Remove workaround in Wheel.cpp where we are setting the drive wheel with a scaled percent output rather than telling it how fast to go

**Comment by RadiantRanger26** [comment]
hey I could work on this, I mentioned it at the ROHM meeting - would the point be to make the bot less jittery?

**Comment by CrashTestCoder** [comment]
It would make the wheels less likely to slip

**Comment by CrashTestCoder** [comment]
3 options as I see it
1) find an example of someone's else's code where they got it working
2) find in the correct instructions in the talon fx documentation
3) call/email ctre and ask them for help

**Comment by MrRedness** [comment]
Ok I'm probably going to have to email or search for working code but I started by trying to replicate the original code which caused the issue in the first place and then we can work from there. (branch: velocity)

**Comment by CrashTestCoder** [comment]
drive ratio is a conversion to from encoder ticks to a more reasonable unit from the motor
