### ISSUE TITLE
Bug with Targeting safety

### ISSUE THREAD

**Issue by CrashTestCoder** [TEAM1771/2021-Code#6]
When camera doesn't see the goal or the turret isn't pointed at the goal it wont let you shoot (good) 
but if you try it will still reset the number of balls (bad)

**Comment by MrRedness** [comment]
This seems a little simpler; I'll try to work on it.

**Comment by MrRedness** [comment]
Suggestion: Replace else if with else?

**Comment by CrashTestCoder** [comment]
replacing else if with else would make it spam the debug terminal with warnings "Stop not called after shooting: Indexer Aborting\n",  though technically it would still work. It also doesn't solve this issue. But I do think that messing with that else if block may be a good idea and you could allow it to index if the shoot button is pressed but it doesn't see the goal. But this is a separate issue. (I don't think that issue is worth creating a new separate issue seeing as it is so intimately related to this issue)

I would recommend that you start by looking for where the number of balls in the bot is reset and working back from there

**Comment by MrRedness** [comment]
Ok how about using the invalidStopFlag boolean set to true in the Hopper::shoot method and encasing Hopper::stop in an if block? This way it would only attempt to stop shooting if it is already shooting. (I committed this in the Target-Reset-#Balls branch.)

Btw I'll try to work tonight on some of the other issues and maybe call you on discord.
